### ISSUE TITLE
Functional tests doesn't provide a reliable feedback about the application state

### ISSUE THREAD

**Issue by enzoz** [TWtablero/tablero#196]
They're not providing a reliable feedback about the impact of code base changes.

Sometimes they're failing, sometimes there are timeout errors and sometimes they pass, all of this without any changes or with non-related changes.

**Comment by barboza** [comment]
The enviroment configuration is bad too. The repos and test user variables are set in the environment instead of getting from the config.json. And the local instance of the software has to be configured to the test repos.

Maybe we can change it to be all set from the config.json and have the functional tests open a test app.
